# Official NanoPi R28S board configuration, Debian 13 minimal image.
BOARD=nanopi-r28s
BRANCH=vendor
RELEASE=trixie
BUILD_MINIMAL=yes
BUILD_DESKTOP=no
KERNEL_CONFIGURE=no
EXPERT=yes
COMPRESS_OUTPUTIMAGE=sha,img
SHARE_LOG=no
HOST=emmc-studio
